# Site settings
title: "Relativity Transit" 
email: ogderoge@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Relativity Transit is a weblog about programming, photography, design, and more written by Roger Ogden.
url: "http://rogerogden.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: _rogerogden
github_username:  rogerogden

# Build settings
markdown: kramdown
